# Generated by Django 5.0.7 on 2024-07-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='content',
            new_name='jobDescriptionContent',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='title',
            new_name='jobDescriptionTitle',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='resumeContent',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='title',
            new_name='resumeTitle',
        ),
    ]
