# Generated by Django 5.0.7 on 2024-07-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_jobdescription_jobdescriptioncontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='jobDescriptionContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='jobDescriptionTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resumeContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resumeTitle',
            new_name='title',
        ),
    ]
